### ISSUE TITLE
Directory thumb and directory cache not writeable

### ISSUE THREAD

**Issue by Bart274** [sbdomo/MyReadings#1]
Hi,

When I run the compatibility tests I get two errors stating that the directory thumb and the directory cache aren't writeable.
How can I fix this?
I'm running your software on Ubuntu 12.04LTS and I have given all right to both my MyReadings and my Calibre directories.

Sincerely,
Bart

**Comment by sbdomo** [comment]
Hello,
You must have two directories in MyReadings : cache and thumb.
First question:
What version of MyReadings did you use? That of github is the version of development. In this version, it is necessary to add these two directories.
The version of "production", which is compiled, is on my blog (http://sbdomo.esy.es/) and there is that two directories in.
cache is use for the cbz viewer (pages your are readings are in that directory).
thumb is use for thumbnails of books in access mode "resize and cache".
Php server must be able to write in that directories. tests.php use the command "is_writeable" to test it.

**Comment by Bart274** [comment]
Hi,

I was using the development version of github. I didn't know I needed to add those two directories myself. After I created them, my tests no longer fail. :)
Thanks for the help! :)

**Comment by sbdomo** [comment]
The production version is faster, you should use it.
These two directories are not on github to prevent to put on github all files in these cache.
