### ISSUE TITLE
error on admin.php on tests Rar extension not loaded (you can't use cbr viewer)

### ISSUE THREAD

**Issue by hugoheitz** [sbdomo/MyReadings#10]

**Comment by hugoheitz** [comment]
I have this error. I dont know what I have to do to be able to use cbr viewer.
Can you add this information to the FAQ ?

**Comment by Bart274** [comment]
you'll need to enable the php-rar extension of your webserver.

I don't have this working on my server either. My php-rar extension should be loaded but the test always fails and when I try to open a cbr-file, I get an error the my archive is faulty.

**Comment by sbdomo** [comment]
Yes,
It's php-rar extension which is need. I can't help you more. This work on the server where I put a demo of My Readings but not in my home : I have a NAS Synology and on this it seems very difficult to install that extension...
It's easier to have Php-zip for cbz...

**Comment by sbdomo** [comment]
For Bart274,
Did you try to use on your server, the cbr which is on my demo : The woman in red,  here: http://sbdomo.esy.es/MyReadings/
To see if it's the cbr or your server...

**Comment by hugoheitz** [comment]
conclusion :
use CBZ instead of RAR
better in every aspect (metatagging with comicrack, indexation with calibre, access with myreadings)
