### ISSUE TITLE
Unable to click on epub download button or read epub on smartphone due to window size

### ISSUE THREAD

**Issue by hugoheitz** [sbdomo/MyReadings#12]
context :
on my smartphone.

I see MyReadings interface.

I want to download or read an ebook.

when I click on the book, it opens a window with informations about the book.
At the base of the windows, there is a button to download (epub) and a button to read directly (using the viewer).
The size of the windows is too big and I cant click on the buttons because when I try to move down and let go, the window go up automatically.

potential solutions :
open an other window (ie : on the explorer) which is scrollable ?
put the buttons on the top ?

thanks,
Hugo

**Comment by sbdomo** [comment]
Yes,
I managed to reproduce this bug on some navigators (as Firefox).
I try to find why.

**Comment by sbdomo** [comment]
I think that it is the animation of the panel when this one opened which created this bug.
I removed this animation.
This maybe tested with the last commit.

**Comment by hugoheitz** [comment]
Hi,

Thanks,

How can I get the last commit directly on the syno ?
Is there an easy way to do it ?

Or do I need to get the last commit on my mac and upload it on the syno ?

thanks for your help,
Hugo
2014-05-24 8:43 GMT+02:00 sb domo notifications@github.com:

**Comment by sbdomo** [comment]
The version on github is not the "production" version intended for all the users. It is the complete "development" version. It is bigger and slower at start up.
I advice thus to put it besides the normal version to use it only as "beta" test.
To put it on the server and keep it up to date, it is possible to use Github. I use Github for Windows. There is a package for NAS but I do not know its possibilities.
Otherwise, a solution is to copy everything by hand...

**Comment by hugoheitz** [comment]
Bonjour,

Après vérification, le seul package fourni "en standard" par Syno est le
package "Git Server", mais il contient
bien évidemmen un "client" git

## 1/ Installation du package "Git Server"

Se logguer sur l'interface Web du Syno et cliquer sur:
Packages Center -> Utilities -> Git Server

## 2/ Cloner le repository de MyReadings:
- se mettre dans le repertoire adequat
- lancer la commande suivante:
  nas> git clone https://github.com/sbdomo/MyReadings.git
  Cloning into 'MyReadings'...
  remote: Reusing existing pack: 3357, done.
  remote: Total 3357 (delta 0), reused 0 (delta 0)
  Receiving objects: 100% (3357/3357), 17.67 MiB | 704.00 KiB/s, done.
  Resolving deltas: 100% (693/693), done.
  Checking connectivity... done.
  nas> ls -ld MyReadings/
  drwxr-xr-x    9 root     root          4096 May 29 00:14 MyReadings/
  et voila

## 3/ Virer la casse et donner un nom "Beta":

renommer le repertoire pour éviter tout probleme d'accès, lorsqu'on passe
par le web:
nas> mv MyReadings myreadings-dev

## 4/ Mise à jour de ton repository Git:

Place toi dans donc dossier GIT et lance "git pull"
nas> pwd
/volume1/web/myreadings-dev
nas> git pull
Already up-to-date.
nas>
Dans mon cas, le repo est à jour, donc il ne fait rien.

J'ai essaye ensuite de faire la config en ligne
ds /myreadings-dev/admin.php

j'accede a la page mais j'ai une erreur ensuite que je n'ai pas le temps de
voir.
peut etre un pb de droits ?
je verifie ce soir.

en tout cas je voulais partager la technique concernant le git directement
sur le NAS.

a bientot,
Hugo

2014-05-28 9:57 GMT+02:00 sb domo notifications@github.com:

**Comment by sbdomo** [comment]
Intéressant. Dommage qu'il ne semble pas y avoir d'interface web (par exemple dans DSM) pour éviter la gestion de github par ligne de commande. Mais ça semble pratique...
Merci du retour...

**Comment by hugoheitz** [comment]
j'essaie de mettre ca en place pour ameliorer les perfs et soulager le PHP

en me basant sur la FAQ
http://sbdomo.esy.es/2014/05/my-readings-configuration-dsm5/#more-168

mais y a un truc bizarre

la ligne fournie par defaut, sans / en fin de repertoire

XSendFilePath /var/services/web /var/services/homes
la ligne proposee avec le / en fin de repertoire
XSendFilePath /volume1/

j' avais essaye ca ne marchait pas.
j'ai donc essaye

XSendFilePath /volume1 /var/services/web /var/services/homes

test pour voir si ca marche d'office (en allant sur admin.php)

[Tue Jul 08 00:49:32 2014] [error] [client 192.168.1.102](20023)The given
path was above the root path: xsendfile: unable to find file:
/volume1/calibre/_calibre_dev_BDs/Derib/Yakari (1)/cover.jpg, referer:
http://192.168.1.101/myreadings-dev/admin.php

[Tue Jul 08 20:00:54 2014] [error] [client 192.168.1.102](20023)The given
path was above the root path: xsendfile: unable to find file:
/volume1/calibre/_calibre_prod_ebooks/Braunbeck, Gary A_/Mais c'est a toi
que je pense (240)/cover.jpg, referer:
http://192.168.1.101/myreadings/admin.php

arret

[Tue Jul 08 20:01:26 2014] [notice] caught SIGTERM, shutting down
relance

la relance echoue
[image: Images intégrées 1]

je pense que je vais solliciter le dev...

des idees ?

merci pour votre retour,

**Comment by hugoheitz** [comment]
LoadModule xsendfile_module modules/mod_xsendfile.so

XSendFile on

XSendFilePath /volume1

#/var/services/web /var/services/homes

SetEnv MOD_X_SENDFILE_ENABLED yes

il ne faut pas de / a la fin de volume1

test OK.

est ce que vous pouvez modifier la page de FAQ ?

merci

**Comment by sbdomo** [comment]
Il faudra que je fasse des tests car je ne suis pas du tout spécialiste de la syntaxe du xsenfilepath, je pensais avoir mis un / dans ma config...
Mais ce ne sera pas tout de suite. Je ne suis pas chez moi (en vacances...).

**Comment by hugoheitz** [comment]
Bonjour,

Voici le 1er jet du package MyReadings pour Synology [?] # YES !

Il a été testé dans un XPenology / Virtualbox !
cf la photo : COPS + MyReadings !

Pour construire ce package : reprise du package de COPS dans spksrc et j'ai
juste changé ce qu'il fallait pour que ca pointe vers la bonne URL, le bon
format (.zip) etc..etc..

Le package est en pièce jointe. C'est la version 0.4.3 et pas la version
GIT car la 0.4.3 est compilée et donc plus rapide.

Comme c'est le package de COPS, il demande le repository Calibre juste
apres l'install
En principe, ca sert pas, mais dans le doute, rentre la bonne valeur, ca
coute pas plus cher.

Ensuite, tu cliques sur le lien, et la.... t'as rien, puisqu'il faut
configurer :

http://@ip-de-mon-nas/myreadings/admin.php

Tu te crées un compte d'admin et tu rajoutes le répository Calibre dans la
conf MyReadings, mais bon, tout ça tu sais faire, tu l'as déjà fait.
Tu n'as plus qu'a installer le package à la main et me faire un retour.

Ce qui serait top, c'est de le proposer à synocommunity...

cordialement,
Hugo Heitz
