### ISSUE TITLE
No directories : cache or thumbs when getting the last version with git

### ISSUE THREAD

**Issue by hugoheitz** [sbdomo/MyReadings#13]
When I get the last dev version from GIT, there is no directory : 
cache
thumbs

I assume it's because there is no file at all in it.

when I configure myreadings, I get errors on thumbs because the directory doesnt exist, same with cache.

Proposal : can you put a file (info.txt explaining the role of the directory) in each directory so git will create the directory when downloading ?

**Comment by sbdomo** [comment]
In fact, I have put that type of files for the production version for some directories.
On github, the problem is that my cache and thumb directories are not empty (my covers and pages are in when I test My Readings). As these files don't have to be on github, I ask to github to not put that two directories.
It's just I don't know how to ask to put a directory but not its files.

**Comment by hugoheitz** [comment]
Salut,

j'ai un ami qui participe au debug et aux essais.

il connait bien GIT, il a trouve la solution :
Tu crées un fichier texte qui s'appelle ".gitignore" (sans les guillemets)
que tu places dans le ou les répertoires a exclure
Dans ce fichiers, tu mets les 2 lignes suivantes :
*
!.gitignore
- pour lui dire de commiter aucun fichier SAUF le fichier .gitignore lui
  même, vu que git ne sait pas commiter des répertoires vides

Une belle astuce qui marche nickel :)

explication complete :
http://stackoverflow.com/questions/4250063/how-to-gitignore-all-files-folder-in-a-folder-but-not-the-folder-itself

ca permettra d'avoir une version up to date de myreadings pour les essais.
super.

on continue le debug.

derniere remontee :
ca marche pas avec un ipod touch.
j'essaie d'avoir plus d'infos.

a bientot

2014-06-05 17:24 GMT+02:00 sb domo notifications@github.com:

**Comment by sbdomo** [comment]
Merci pour l'info. Ces fichiers seront ajoutés.
pour l'ipod je ne peux pas vérifier. C'est peut-être lié à une vieille version d'iOs.

**Comment by sbdomo** [comment]
C'est fait. J'ai appliqué la méthode mais avec le gitignore à la racine...
