### ISSUE TITLE
improve user/password in admin.php

### ISSUE THREAD

**Issue by hugoheitz** [sbdomo/MyReadings#8]
in the admin.php

user / password is asked in plain text.

can you implement 2 boxes in html password formular to type the password and confirm it ?

**Comment by sbdomo** [comment]
I could and I asked myself the question without having really decided at the moment.
It's just that it's the admin page (which is not public) and I use it to read the password if I have forgot it...

**Comment by hugoheitz** [comment]
The admin page is not public but when you access it from the computer used to configure myreadings it offers you via autocompletion the password in plain text.
I think it s a small evolution and better security.

**Comment by sbdomo** [comment]
OK,
The autocompletion is a problem. I had not thought of that.
I will change that.

**Comment by hugoheitz** [comment]
change is OK but the informations are now passed from form to page using GET method so the password is readable in the URL, can you change to POST method ?

**Comment by sbdomo** [comment]
Yes,
I will try POST method. (It's not a protection, because you can find password in console for exemple, but it's less visible...)

**Comment by hugoheitz** [comment]
thanks
ready to test when you'll say it's avaiable

**Comment by sbdomo** [comment]
You can try the last commit.
All must be ready for a new 0.4.2 release...

**Comment by hugoheitz** [comment]
I just tried.

It doesnt seem to work.

maybe PHP caching issue.

I will try to disable it and see.

2014-06-11 8:58 GMT+02:00 sb domo notifications@github.com:

**Comment by sbdomo** [comment]
It's perhaps not only php cache. In the new version, I made several modification which return the update less transparent than usually:
To allow to personalize the styles css of the main screen, I put them in index.html, it is necessary to force the refresh of this page in the browser to use these styles.
For the management of custom column, I changed the management of databases. You can have an error message during the first opening. It is necessary to close and to open My Readings again.

**Comment by hugoheitz** [comment]
it was user ownership of the files.
now modified it works fine.
I confirm that the user/password cant be read directly within the URL.
you can close the issue.
