### ISSUE TITLE
configuration in db ? (anywhere but php file)

### ISSUE THREAD

**Issue by hugoheitz** [sbdomo/MyReadings#9]
the modifications made to the configuration are saved in
config.php

when the cache is on, there is a latency before changes are taken in account.

can you save the configuration in db ? (or in another file format).

**Comment by sbdomo** [comment]
There is a problem with update latency of the config.php file if a cache of php server is on.
I did not find solution to deactivate temporarily this cache or force the update to use it in admin.php.
This has effect only during the configuration of My Readings what should not be frequent and I recommend, in this case, to deactivate temporarily the cache in the server, the time to update the configuration.
There is now a sqlite db (/config/conf.db) which is used to save some parameters (bookmarks). However, to prevent an external user from reaching private parameters (password, path of databases...), I put them in a php file (and not in a file with a format which could give is content).
If someone have a better solution, I'll try it...

On the other hand, during the use of My Readings, the config.php file is used by every call of php (to verify the login/password). The cache of this file, in this case, is useful and it is a better/faster solution than to have to launch a request towards a database.

**Comment by hugoheitz** [comment]
I dont want to use login/password. That's maybe why I dont see the better/faster solution aspect of this use.
I just want to be able to configure myreadings and offer it for other members of my family to be able to access it.

**Comment by hugoheitz** [comment]
OK.
I now host a dev and a prod myreadings.
Because of the dev part, I have PHP Cache disabled.
Is there a way to crypt the content of the informations in the SQLite db to avoid use of config.php to store informations ?

**Comment by sbdomo** [comment]
Hello,
A solution could be to use .htaccess protection but with another of my programs (MyVera), I noticed that a lot of users have difficulties to use htaccess. They do not manage to configure their server (in particular under IIS).
